Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
dev_block.c
dev_mmcsd_core.c
dev_sd.c
dev_sdio.c
dev_mmc.c
""")

# The set of source files associated with this SConscript file.
path = [cwd + '/../include' , cwd + '/sdhci/include']

if GetDepend('RT_USING_SDHCI'):
    src += [os.path.join('sdhci', 'sdhci.c')]
    src += [os.path.join('sdhci', 'fit-mmc.c')]
    src += [os.path.join('sdhci', 'sdhci-platform.c')]

# Add ESP32 SDIO AT driver
if GetDepend('RT_USING_ESP32_SDIO_AT'):
    src += ['drv_esp32_sdio_at.c']
    src += ['drv_esp32_sdio_probe.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SDIO'], CPPPATH = path)

Return('group')
