Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd + '/include']

if GetDepend('RT_USING_SDIO'):
    if GetDepend('RT_USING_DFS'):
        src += ['dev_block.c']
    src += ['dev_mmcsd_core.c', 'dev_sd.c', 'dev_sdio.c', 'dev_mmc.c']

    if GetDepend('RT_USING_SDHCI'):
        src += Glob('sdhci/*.c')

    # ESP32 SDIO AT Driver
    if GetDepend('RT_USING_ESP32_SDIO_AT'):
        src += ['drv_esp32_sdio_at.c', 'esp32_at_api.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SDIO'], CPPPATH = CPPPATH)

Return('group')
